#!/bin/bash

# Comprobar si se proporcionaron los nombres de archivo como argumentos
if [ $# -ne 2 ]; then
    echo "Uso: $0 <archivo_origen> <archivo_destino>"
    exit 1
fi

# Asignar nombres de archivo a variables
archivo_origen="$1"
archivo_destino="$2"

# Comando de compilación con pandoc
pandoc "$archivo_origen" -o "$archivo_destino" --from markdown --template ~/pandoc-latex-template-master/eisvogel.tex --listings -N --toc --variable urlcolor=cyan --filter pandoc-latex-environment

# Comprobar si la compilación fue exitosa
if [ $? -eq 0 ]; then
    echo "Compilación exitosa: $archivo_destino generado."
else
    echo "Error durante la compilación."
fi
